version: "2"

services:

  apache:
    image: eeacms/apache:2.4-1.0
    ports:
    - "80:80"
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      SERVER_ADMIN: "helpdesk@wise-test.eionet.europa.eu"
      SERVER_NAME: "wise-test.eionet.europa.eu"
      RewriteRule: "^/(.*) http://plone:8080/VirtualHostBase/http/wise-test.eionet.europa.eu:80/VirtualHostRoot/$$1 [P,L]"
      TZ: "Europe/Copenhagen"

  plone:
    # image: eeacms/plone-wise:0.2
    # build: ./devel/
    build: .
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - zeoserver
    - memcached
    environment:
      ZOPE_MODE: "zeo_client"
      TZ: "Europe/Copenhagen"
    volumes:
    - wise-downloads:/data/downloads
    - wise-plone-data:/data
    - ./src:/plone/instance/src/
    - ./buildout.cfg:/plone/instance/buildout.cfg
    ports:
      - "8090:8080"
    command: bash -c "tail -f /dev/null"

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - "-m"
    - "2048"

  zeoserver:
    image: plone:4.3.10
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - zeoserver
    volumes:
    - wise-data:/data

volumes:
  wise-plone-data:
  wise-async-data:
  wise-data:
  wise-downloads:
