version: "2.1"

services:

  plone:
    image: "${BACKEND_IMAGE:?no such variable}"
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
      - zeo
      - memcached
    ports:
      - "${BACKEND_PORT:-8085}:8080"
    environment:
      TZ: "Europe/Copenhagen"
      ZEO_ADDRESS: "zeo:8080"
      ZOPE_MODE: "zeo_client"
    entrypoint: sh -c "tail -f /dev/null"

  zeo:
    image: "${BACKEND_IMAGE:?no such variable}"
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
      ZOPE_MODE: "zeo"
    command:
      - zeo

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
      - "-m"
      - "2048"

  msdb:
      image: microsoft/mssql-server-linux:latest
      ports:
        - "1433:1433"
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: bla3311!
        MSSQL_PID: Enterprise
      volumes:
        - ./db:/shared/


# backend demo-forests-p5-plone
# http-request set-path /VirtualHostBase/https/demo-forests-p5.eea.europa.eu:443/fise/VirtualHostRoot/_vh_api/%[path,regsub(\/api,,g)]
