version: "2"
services:

  zeo:
    volumes:
      - ./data:/data

  shell:
    build: ./plone
    depends_on:
      - memcached
      - zeo
    environment:
      ZOPE_MODE: "zeo_client"
      ZEO_ADDRESS: "zeo:8080"
      TZ: "Europe/Copenhagen"
    env_file:
      - env.secret
    entrypoint: bash -c "tail -f /dev/null"
    tty: true
    stdin_open: true
    ports:
    - 3080:8080
    volumes:
    - ./plone/site.cfg:/plone/instance/site.cfg
    - ./src/:/plone/instance/src/

  zeo:
    # command: bash -c "tail -f /dev/null"
    volumes:
      - ./data:/data

  plone:
    # image: tiberiuichim/wise-plone5:0.1
    build: ./plone
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
      - zeo
      - memcached
    ports:
      - "8086:8080"
    # entrypoint: sh -c "tail -f /dev/null"
    environment:
      TZ: "Europe/Copenhagen"
      ZEO_ADDRESS: "zeo:8080"
      ZOPE_MODE: "zeo_client"
    volumes:
    - ./src/:/plone/instance/src/
    - ./plone/site.cfg:/plone/instance/site.cfg
    # - ./data:/data

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
      - "-m"
      - "2048"

  # msdb:
  #   image: microsoft/mssql-server-linux:latest
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: bla3311!
  #     MSSQL_PID: Enterprise
  #   volumes:
  #     - msdb:/var/opt/mssql/data/
  #     - ./db:/shared-db/

volumes:
  data:
    driver: local
  msdb:
    driver: local
