version: "2"
services:

  plone:
    image: tiberiuichim/wise-plone5:5.2-0.2
    depends_on:
      - memcached
      - postfix
      - zeo
    environment:
      ZOPE_MODE: "zeo_client"
      TZ: "Europe/Copenhagen"

  zeo:
    image: plone:5.2-python2
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
      ZOPE_MODE: "zeo"
    command:
      - zeo

  # async:
  #   image: eeacms/plonesaas:5.1.5-67
  #   depends_on:
  #   - memcached
  #   - postfix
  #   environment:
  #     ZOPE_MODE: "zeo_async"
  #     TZ: "Europe/Copenhagen"

  memcached:
    image: memcached:1.5.12
    command:
    - "-m"
    - "2048"
    environment:
      TZ: "Europe/Bucharest"

  postfix:
    image: eeacms/postfix:2.10-3.3
    environment:
      MTP_HOST: "avoinea.com"
      TZ: "Europe/Bucharest"

  #added msdb and msdb-shell from WISE.
  msdb:
    image: microsoft/mssql-server-linux:latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: bla3311!
      MSSQL_PID: Enterprise
    volumes:
      - msdb:/var/opt/mssql/data/

volumes:
  data:
    driver: rancher-nfs
  msdb:
    driver: rancher-nfs
